Update file bd mysql
ZingerXY/keyboardTrainer pull request #107
Opened 2023-02-10 13:17 UTC by EvgeniyKorshov

обновлена база можете столкнуться с оишбками ,были изменены поля username на name  и тд проверьте фронт чтобы все работало

2023-02-10 13:22 UTC, AnastasiyaVi approved these changes

2023-02-10 13:28 UTC, ZingerXY requested changes
Убери, пожалуйста, лишние строки в дампе бд

2023-02-10 13:28 UTC, ZingerXY commented on server/bd_mysql.sql
> +INSERT INTO `statistics` (`player_id`,`task_id`,`time`,`typed_characters`,`number_of_errors`,`Accuracy`,`dial_speeds`)
Почему тут 2 инсерта в statistics с разынми полями старое наверно надо удалить

2023-02-10 13:28 UTC, ZingerXY commented on server/bd_mysql.sql
> +INSERT INTO `users` (`name`,`email`,`password`,`created_at`)
Зачем эта строка?

2023-02-12 17:52 UTC, ZingerXY approved these changes

2023-02-12 17:52 UTC, merged